# PWHL Attendance

## Overview

As women’s sports gain popularity, I am interested in the evolution of game attendance over time. I am particularly interested in the case of the Professional Women’s Hockey League (PWHL).

## Introduction

I had the chance to witness the Montreal Victoire’s first home game, on January 13, 2024. The team did not have a name yet and was simply referred to as "PWHL Montreal". The game was held at the Verdun auditorium, the 4043-seat venue where the Victoire trains. The ambiance was amazing.

While the Victoire still trains in Verdun, the team now holds all of its regular home matches in a bigger venue, Place Bell, which can accomodate 10,062 spectators.

As women’s hockey gains popularity and athletes are getting paid full-time salaries to train together, we are seeing a higher level of play than ever before. I hope the attendance numbers will be maintained over time or even grow, ensuring the PWHL’s future and setting an example which, I hope, will lead to better funding for women’s sports and high level female athletes flourishing.

## Dataset

### Data source

The PWHL’s website’s [schedule page](https://www.thepwhl.com/en/stats/schedule/all-teams/5/all-months) lists all games for the current season in a table.

![the top of a table titled Schedule and listing the date, time, teams, scores, venues and broadcasters for PWHL games](./img/2025-04-07_ScheduleTable.png)

The R button at the end of each line leads to a webpage containing an official game report which specifies, among other things, the venue, date, teams and attendance.

The current season is selected by default but it is possible to obtain the same table for past seasons.

It is therefore possible to use the webpage to get a list of URLs corresponding to game reports for all of a season’s games. Then, information can be collected from each of the reports, which appear to all be formatted in the same way.

### Data scraping

I scraped a list of game report links from each season’s webpage. Then, I scraped the following information from each report, storing it in a DataFrame: visiting team, home team, venue, date, game start and attendance.

In [4]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [6]:
game_report_urls = []

def scrape_game_report_urls(url):
    game_report_urls = []
    # set up the WebDriver
    driver = webdriver.Chrome() #EDIT THIS LINE if not using Chrome <<<<<<<<<<<<<<<<<<<< IMPORTANT <<<<<<<<<<<<<<<<<<<<
    # open the webpage
    driver.get(url)
    # wait for the table to load
    try:
        table = WebDriverWait(driver, 2).until(
            EC.presence_of_element_located((By.XPATH, '//table'))
        )
        all_links = driver.find_elements(By.XPATH, "//a[@href]")
        for link in all_links:
            link_url = link.get_attribute("href")
            if "official-game-report" in link_url:
                game_report_urls.append(link_url)
    finally:
        driver.quit()
    return game_report_urls

for i in range(1, 7): # currently, there are 6 seasons
    game_report_urls.extend(scrape_game_report_urls("https://www.thepwhl.com/en/stats/schedule/all-teams/" + str(i) + "/all-months"))

In [8]:
game_report_urls[0:5]

['https://lscluster.hockeytech.com/game_reports/official-game-report.php?client_code=pwhl&game_id=2&lang_id=1',
 'https://lscluster.hockeytech.com/game_reports/official-game-report.php?client_code=pwhl&game_id=3&lang_id=1',
 'https://lscluster.hockeytech.com/game_reports/official-game-report.php?client_code=pwhl&game_id=4&lang_id=1',
 'https://lscluster.hockeytech.com/game_reports/official-game-report.php?client_code=pwhl&game_id=5&lang_id=1',
 'https://lscluster.hockeytech.com/game_reports/official-game-report.php?client_code=pwhl&game_id=6&lang_id=1']

Now that I have the URL for each report, I want to extract specific information: visiting team, home team, venue, date, game start and attendance.

In [10]:
import re
import requests 
from bs4 import BeautifulSoup as bs

In [77]:
def get_game_info(url):
    game_info = {}
    regex = r"#.{0,2}\d+ (.+) \d+ at (.+) \d+  (.+) (\w+ \d+, \d+)"
    # scrape data
    r = requests.get(url) 
    soup = bs(r.content)
    table = soup.select('table')[0]
    game_data = pd.read_html(str(table))[0]
    # find all required values
    text = game_data.iloc[0][1]
    captures = re.findall(regex, text)
    if len(captures) > 0:
        if len(captures[0]) >= 4:
            game_info["visiting team"], game_info["home team"], game_info["venue"], game_info["date"] = captures[0]
        else:
            print("Problem with captures ", captures[0])
    else:
        print("Problem with url ", url)
    game_info["game start"] = game_data.iloc[4][1]
    game_info["attendance"] = game_data.iloc[7][1]
    return game_info

In [79]:
get_game_info("https://lscluster.hockeytech.com/game_reports/official-game-report.php?client_code=pwhl&game_id=105&lang_id=1")

{'visiting team': 'Boston',
 'home team': 'Toronto',
 'venue': 'Coca-Cola Coliseum',
 'date': 'Nov 30, 2024',
 'game start': '2:15 PM EST',
 'attendance': '8089'}

Let’s go and get the info from all the game reports.

In [112]:
import warnings
warnings.filterwarnings('ignore')

In [114]:
games = []
for url in game_report_urls:
    new_data = get_game_info(url)
    games.append(new_data)

In [115]:
len(games)

202

In [219]:
df = pd.DataFrame(games)
df

,visiting team,home team,venue,date,game start,attendance
0,New York,Toronto,Mattamy Athletic Centre,"Jan 1, 2024",12:48 PM EST,2537
1,Montreal,Ottawa,TD Place,"Jan 2, 2024",7:12 PM EST,8318
2,Minnesota,Boston,Tsongas Center,"Jan 3, 2024",7:14 PM EST,4012
3,Toronto,New York,Total Mortgage Arena,"Jan 5, 2024",7:15 PM EST,2152
4,Montreal,Minnesota,Xcel Energy Center,"Jan 6, 2024",2:42 PM CST,13316
...,...,...,...,...,...,...
197,Montréal,Ottawa,TD Place,"May 16, 2025",7:07 PM EST,8011
198,Minnesota,Ottawa,TD Place,"May 20, 2025",7:16 PM EST,6184
199,Minnesota,Ottawa,TD Place,"May 22, 2025",7:15 PM EST,8206
200,Ottawa,Minnesota,Xcel Energy Center,"May 24, 2025",4:16 PM CST,8098
201,Ottawa,Minnesota,Xcel Energy Center,"May 26, 2025",4:16 PM CST,11024

### Adding features

To see how filled each venue was during each match, I obtained seating capacity information and added it to the data.

In [222]:
CAPACITIES = {"Xcel Energy Center": 18300,
             "Tsongas Center": 6500,
             "TD Place": 9862,
             "Place Bell": 10062,
             "Prudential Center": 16514,
             "Coca-Cola Coliseum": 7851,
             "Mattamy Athletic Centre": 2600,
             "Verdun Auditorium": 4043,
             "Utica University Nexus Center - Mastrovito Hyundai": 1200,
             "UBS Arena": 17225,
             "Total Mortgage Arena": 8412,
             "Ford Performance Centre": 200,
             "Agganis Arena": 6150,
             "Little Caesars Arena": 19515,
             "Bell Centre": 21273,
             "Scotiabank Arena": 18800,
             "Videotron Centre": 18259,
             "Lenovo Center": 18680,
             "KeyBank Center": 18595,
             "Rogers Place": 18347,
             "Canadian Tire Centre": 19153,
             "Ball Arena": 18007,
             "Rogers Arena": 18910,
             "Climate Pledge Arena": 17200,
             "PPG Paints Arena": 18187,
             "3M Arena at Mariucci": 10257,
             "Enterprise Center": 18096}

def get_capacity(venue):
    hockey_seats = -1 #will return -1 if the venue is not known
    if venue in CAPACITIES.keys():
        hockey_seats = CAPACITIES[venue]
    return hockey_seats

In [224]:
df["seating capacity"] = df.apply(lambda row: get_capacity(row["venue"]), axis=1)

The day of the week can impact attendance. Typically, Friday, Saturday and Sunday games have the most spectators. So let’s add a "weekday" column.

In [227]:
from dateutil import parser
from datetime import datetime
DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
df["date"] = df.apply(lambda row: parser.parse(row["date"]), axis=1)

In [229]:
df["weekday"] = df.apply(lambda row: DAYS[row["date"].weekday()], axis=1)
df

,visiting team,home team,venue,date,game start,attendance,seating capacity,weekday
0,New York,Toronto,Mattamy Athletic Centre,2024-01-01,12:48 PM EST,2537,2600,Monday
1,Montreal,Ottawa,TD Place,2024-01-02,7:12 PM EST,8318,9862,Tuesday
2,Minnesota,Boston,Tsongas Center,2024-01-03,7:14 PM EST,4012,6500,Wednesday
3,Toronto,New York,Total Mortgage Arena,2024-01-05,7:15 PM EST,2152,8412,Friday
4,Montreal,Minnesota,Xcel Energy Center,2024-01-06,2:42 PM CST,13316,18300,Saturday
...,...,...,...,...,...,...,...,...
197,Montréal,Ottawa,TD Place,2025-05-16,7:07 PM EST,8011,9862,Friday
198,Minnesota,Ottawa,TD Place,2025-05-20,7:16 PM EST,6184,9862,Tuesday
199,Minnesota,Ottawa,TD Place,2025-05-22,7:15 PM EST,8206,9862,Thursday
200,Ottawa,Minnesota,Xcel Energy Center,2025-05-24,4:16 PM CST,8098,18300,Saturday
201,Ottawa,Minnesota,Xcel Energy Center,2025-05-26,4:16 PM CST,11024,18300,Monday

### Data cleaning

Tickets are not sold for preseason games so there is no attendance. I chose to remove the rows corresponding to these games from the dataset.

In [232]:
df.drop(df[df["attendance"] == "-"].index, inplace=True)

I noticed that the spelling of "Montreal" isn’t always the same.

In [235]:
df["visiting team"].value_counts().tail(3)

visiting team
Montréal     14
Montreal     13
MontrÃ©al     3
Name: count, dtype: int64

In [321]:
mtl_visit_accent = df["visiting team"].isin(["Montréal", "MontrÃ©al"])
mtl_home_accent = df["home team"].isin(["Montréal", "MontrÃ©al"])
df.loc[mtl_visit_accent, "visiting team"] = "Montreal"
df.loc[mtl_home_accent, "home team"] = "Montreal"

### Data type

Let’s change the data type of the attendance column from string to integer.

In [324]:
df['attendance'] = pd.to_numeric(df['attendance'], downcast='integer')
df

,visiting team,home team,venue,date,game start,attendance,seating capacity,weekday,sold out
0,New York,Toronto,Mattamy Athletic Centre,2024-01-01,12:48 PM EST,2537,2600,Monday,True
1,Montreal,Ottawa,TD Place,2024-01-02,7:12 PM EST,8318,9862,Tuesday,False
2,Minnesota,Boston,Tsongas Center,2024-01-03,7:14 PM EST,4012,6500,Wednesday,False
3,Toronto,New York,Total Mortgage Arena,2024-01-05,7:15 PM EST,2152,8412,Friday,False
4,Montreal,Minnesota,Xcel Energy Center,2024-01-06,2:42 PM CST,13316,18300,Saturday,False
...,...,...,...,...,...,...,...,...,...
197,Montreal,Ottawa,TD Place,2025-05-16,7:07 PM EST,8011,9862,Friday,False
198,Minnesota,Ottawa,TD Place,2025-05-20,7:16 PM EST,6184,9862,Tuesday,False
199,Minnesota,Ottawa,TD Place,2025-05-22,7:15 PM EST,8206,9862,Thursday,False
200,Ottawa,Minnesota,Xcel Energy Center,2025-05-24,4:16 PM CST,8098,18300,Saturday,False
201,Ottawa,Minnesota,Xcel Energy Center,2025-05-26,4:16 PM CST,11024,18300,Monday,False

### Saving to CSV

Finally, let’s save the data to CSV in case we later want to analyze it without getting it from the PWHL website again.

In [327]:
df.to_csv("games.csv", index=False)

## Analysis

### All teams and venues

I am interested in the games played after the second regular season started, in November 2024.

In [331]:
post_y1_df = df[df["date"] > parser.parse("Nov 1, 2024")]
post_y1_df

,visiting team,home team,venue,date,game start,attendance,seating capacity,weekday,sold out
100,Boston,Toronto,Coca-Cola Coliseum,2024-11-30,2:15 PM EST,8089,7851,Saturday,True
101,Ottawa,Montreal,Place Bell,2024-11-30,5:18 PM EST,10033,10062,Saturday,True
102,New York,Minnesota,Xcel Energy Center,2024-12-01,5:16 PM CST,8022,18300,Sunday,False
103,Toronto,Ottawa,TD Place,2024-12-03,7:15 PM EST,6451,9862,Tuesday,False
104,Minnesota,Boston,Tsongas Center,2024-12-04,7:16 PM EST,3811,6500,Wednesday,False
...,...,...,...,...,...,...,...,...,...
197,Montreal,Ottawa,TD Place,2025-05-16,7:07 PM EST,8011,9862,Friday,False
198,Minnesota,Ottawa,TD Place,2025-05-20,7:16 PM EST,6184,9862,Tuesday,False
199,Minnesota,Ottawa,TD Place,2025-05-22,7:15 PM EST,8206,9862,Thursday,False
200,Ottawa,Minnesota,Xcel Energy Center,2025-05-24,4:16 PM CST,8098,18300,Saturday,False
201,Ottawa,Minnesota,Xcel Energy Center,2025-05-26,4:16 PM CST,11024,18300,Monday,False

First, let’s see, for each venue, how many of the games were likely sold out (the audience may still vary due to scalpers not selling all their tickets or people who bought a ticket not showing up). I decided to set the bar at 90% of the capacity.

In [334]:
post_y1_df["sold out"] = post_y1_df["attendance"] / post_y1_df["seating capacity"] >= 0.9 #creating a column to identify sold out games
soldout_info = post_y1_df.groupby(["venue", "sold out"]).size()
soldout_info

venue                 sold out
Agganis Arena         True         2
Ball Arena            False        1
Bell Centre           False        1
Canadian Tire Centre  False        1
Climate Pledge Arena  False        1
Coca-Cola Coliseum    False        1
                      True        14
Enterprise Center     False        1
KeyBank Center        False        1
Lenovo Center         False        1
Little Caesars Arena  False        1
Place Bell            False       10
                      True         5
Prudential Center     False       13
Rogers Arena          True         1
Rogers Place          True         1
Scotiabank Arena      True         1
TD Place              False       17
Tsongas Center        False        9
                      True         2
Videotron Centre      True         1
Xcel Energy Center    False       17
dtype: int64

We can see here that, in most venues it plays at, the PWHL still has room to grow, getting more fans to attend each game.

The Coca-Cola Coliseum, however, hosted 15 games, 14 of which were sold out, suggesting the league’s popularity has outgrown it and it could be profitable to try and schedule more of Toronto’s future home games in venues capable of accomodating a larger crowd.

### Place Bell, home of the Montreal Victoire

As a Victoire fan, I am particularly interested in the data concerning Place Bell. Tickets were sold out for 5 out of 15 games during the past year. What influences this?

In [338]:
pbell_df = post_y1_df[post_y1_df["venue"] == "Place Bell"] # creating a dataframe with only the matches played at Place Bell

I chose to consider the following factors:

* **The Laval Rocket’s home calendar**: The Rocket’s home is also Place Bell. Naturally, the two teams share some of their fans. While they never play at the same time, they sometimes play on the same day. The Rocket has been very successful over the past year, reaching, like the Victoire, the top rank in its league’s regular season.
* **The Montreal Canadiens’ home calendar**: The Montreal Canadiens are extremely popular and share some of their fans with the Victoire.
* **The weekday**: I believe more people attend hockey matches on Friday nights and weekends than during the week.
* **Holidays**: Not having to work the day of the match or the following day may impact people’s decision to attend.

To take these into account, some features must be added to the dataset.

First, let’s get all the game dates from the Canadien’s 2024-2025 calendar.

In [314]:
ch_game_dates = []
url = "https://www.nhl.com/fr/canadiens/schedule/2024/fullseason"
# set up the WebDriver
driver = webdriver.Chrome() #EDIT THIS LINE if not using Chrome <<<<<<<<<<<<<<<<<<<< IMPORTANT <<<<<<<<<<<<<<<<<<<<
# open the webpage
driver.get(url)
# wait for the tables to load
try:
    table = WebDriverWait(driver, 2).until(
        EC.presence_of_element_located((By.XPATH, '//table'))
    )
    all_dates = driver.find_elements(By.XPATH, "//h3[@id]")
    for date in all_dates:
        info = date.get_attribute("id")
        if info[0:2] != "ot":
            ch_game_dates.append(parser.parse(info))
finally:
    driver.quit()

Next, let’s create a "Canadiens" column to indicate, for each Victoire home match, wether the Canadiens were playing that day.

In [340]:
pbell_df["Canadiens"] = df.apply(lambda row: row["date"] in (ch_game_dates), axis=1)

Now, the Rocket. The Rocket released its season calendar in the form of a [PDF document](https://www.rocketlaval.com/wp-content/uploads/2024/07/Calendrier_2024-25.pdf) showing a small calendar for each month, with different background colors representing home and away matches. I could not find the dates of their series matches on the official website.

I decided to rely on [hockeyDB.com](https://www.hockeydb.com/) instead.

In [370]:
#https://www.hockeydb.com/ihdb/stats/team_results.php?tid=8159&sid=2025    season
#https://www.hockeydb.com/ihdb/stats/playoffdisplay.php?league=ahl1941&season=2025&leaguenm=AHL    playoffs

In [368]:
lr_game_dates = []
url = "https://www.hockeydb.com/ihdb/stats/team_results.php?tid=8159&sid=2025"
# set up the WebDriver
driver = webdriver.Chrome() #EDIT THIS LINE if not using Chrome <<<<<<<<<<<<<<<<<<<< IMPORTANT <<<<<<<<<<<<<<<<<<<<
# open the webpage
driver.get(url)
# wait for the tables to load
try:
    table = WebDriverWait(driver, 2).until(
        EC.presence_of_element_located((By.XPATH, '//table'))
    )
    all_dates = driver.find_elements(By.XPATH, "//h3[@id]")
    for date in all_dates:
        info = date.get_attribute("id")
        if info[0:2] != "ot":
            lr_game_dates.append(parser.parse(info))
finally:
    driver.quit()

In [348]:
pbell_df

,visiting team,home team,venue,date,game start,attendance,seating capacity,weekday,sold out,Canadiens
101,Ottawa,Montreal,Place Bell,2024-11-30,5:18 PM EST,10033,10062,Saturday,True,True
105,New York,Montreal,Place Bell,2024-12-04,7:10 PM EST,5415,10062,Wednesday,False,False
117,Boston,Montreal,Place Bell,2024-12-30,7:08 PM EST,10172,10062,Monday,True,False
130,Minnesota,Montreal,Place Bell,2025-01-17,7:07 PM EST,10172,10062,Friday,True,False
138,Ottawa,Montreal,Place Bell,2025-01-29,7:07 PM EST,6150,10062,Wednesday,False,False
139,Toronto,Montreal,Place Bell,2025-01-30,7:33 PM EST,7242,10062,Thursday,False,True
147,New York,Montreal,Place Bell,2025-02-15,2:13 PM EST,10172,10062,Saturday,True,False
151,Minnesota,Montreal,Place Bell,2025-02-18,7:08 PM EST,6696,10062,Tuesday,False,False
157,Toronto,Montreal,Place Bell,2025-02-25,7:08 PM EST,6101,10062,Tuesday,False,True
160,Minnesota,Montreal,Place Bell,2025-03-04,7:08 PM EST,8923,10062,Tuesday,False,False
173,Toronto,Montreal,Place Bell,2025-03-23,12:08 PM EST,10172,10062,Sunday,True,False
179,New York,Montreal,Place Bell,2025-04-01,7:08 PM EST,8798,10062,Tuesday,False,True
184,Boston,Montreal,Place Bell,2025-04-28,7:09 PM EST,8812,10062,Monday,False,False
191,Ottawa,Montreal,Place Bell,2025-05-08,7:09 PM EST,6570,10062,Thursday,False,False
193,Ottawa,Montreal,Place Bell,2025-05-11,2:08 PM EST,7114,10062,Sunday,False,False

## TODO

- Check if I can find attendance records for the CWHL (prior women’s hockey league) for comparison
- Check if I can find attendance records for other teams with the same home venues for comparison
- Filter for Canadiens home dates

## Note

**Seating capacity values are to be taken with a grain of salt.** Certain venues have different seating capacities for hockey according to different sources. For example, the Verdun Auditorium has either 4114 or 4043 seats. Many venues don’t give specific numbers on their own website. Every time I found a discrepancy between sources, I opted for the (subjectively) most trustworthy source I could find, which was sometimes not that trustworthy, due to the teams and venues not sharing the information themselves (they often use rounded numbers instead). It is also possible that the seating capacity changes over time based on accessible accomodations, DJ booths, etc. [PPG Paints Arena](https://www.ppgpaintsarena.com/ppg-paints-arena/faqs) states that "Due to a flexible curtaining system, the seating capacity of each event will vary." [Ball Arena](https://www.ballarena.com/arena-information/about-ball-arena/) gets a special mention for listing both 18,807 and 18,809 as its hockey seating capacity on the same page.

## Sources

- [3M Arena at Mariucci](https://gophersports.com/sports/2018/5/21/facilities-mariucci-facts-html)
- [3M Arena at Mariucci (IIHF)](https://www.iihf.com/en/events/2026/wm20/static/64811/3m_arena_at_mariucci)
- [About Ball Arena](https://www.ballarena.com/arena-information/about-ball-arena/)
- [About Scotiabank Arena](https://www.scotiabankarena.com/venue-information/about)
- [About the Tsongas Center](https://tsongascenter.com/pages/about-the-tsongas-center)
- [Agganis Arena Capacity & Specifications](https://www.agganisarena.com/business-opportunities/book-the-arena/capacity-specifications/)
- [Auditorium de Verdun (Sporting Events)](https://sports.mtl.org/en/plan/sports-facilities/verdun-auditorium)
- [Bell Centre (Magil Construction)](https://www.magil.com/en/projects/bell-center)
- [Canadian Tire Centre A to Z Guide](https://www.canadiantirecentre.com/guide-a-a-z/)
- [Climate Pledge Arena (Populous)](https://populous.com/showcases/climate-pledge-arena)
- [Coca-Cola Coliseum Seating Chart](https://www.torontocoliseum.com/seating-chart/)
- [Enterprise Center Seat Locator](https://www.enterprisecenter.com/events/seat-locator)
- [Facilities - TMU Athletics & Recreation](https://tmubold.ca/sports/2019/8/22/204964949.aspx)
- [Ford Performance Centre Professional Recreational Hockey Facility](https://www.lakeshorearena.ca/)
- [Laval Rocket Results and Schedule (hockeyDB.com)](https://www.hockeydb.com/ihdb/stats/team_results.php?tid=8159&sid=2025)
- [Little Caesars Arena Information](https://www.detroiteventsarena.com/information/)
- [Montreal Canadiens 2024 Season Schedule](https://www.nhl.com/fr/canadiens/schedule/2024/fullseason)
- [Place Bell - Laval Rocket (Stadium Journey)](https://www.stadiumjourney.com/stadiums/place-bell-laval-rocket)
- [PNC Arena Info (Internet Archive)](https://web.archive.org/web/20141205012555/http://www.thepncarena.com/arena_info)
- [PPG Paints Arena FAQ](https://www.ppgpaintsarena.com/ppg-paints-arena/faqs)
- [Prudential Center Capacity (Arena Capacity)](https://www.arenacapacity.com/prudential-center-capacity/)
- [PWHL](https://www.thepwhl.com/)
- [Rogers Arena (Ticketmaster)](https://blog.ticketmaster.com/step-inside-rogers-arena-vancouver-bc/)
- [Rogers Place (Ticketmaster)](https://blog.ticketmaster.com/step-inside-rogers-place-edmonton-ab/)
- [TD Place Arena (OHL Arena Guide)](https://www.ohlarenaguide.com/67s.htm)
- [Total Mortgage Arena (Ticketsonsale)](https://www.ticketsonsale.com/venues/total-mortgage-arena)
- [UBS Arena (PCI)](https://www.pci.org/PCI/PCI/Project_Resources/Project_Profile/Project_Profile_Details.aspx?ID=253141)
- [Utica University Nexus Center](https://www.nexusutica.com/)
- [Vidéotron Centre, Québec Remparts (QMJHL Arena Guide)](https://www.qmjhlarenaguide.com/remparts.htm)
- [Xcel Energy Center Seating Capacities](https://www.xcelenergycenter.com/assets/doc/Seating_Capacities-e3d7d47c61.pdf)